import { z } from "zod";
import { PARTNER_SINCE_YEAR_MAX, PARTNER_SINCE_YEAR_MIN } from "@shared/partnerSince";
import { teamFormTranslations } from "./translations";

export const TEAM_LABELS: Record<string, string> = {
  name: "Nombre legal completo",
  givenNames: "Nombre(s)",
  firstSurname: "Primer apellido",
  secondSurname: "Segundo apellido",
  slug: "Slug",
  title: "Cargo",
  titleEs: "Cargo (español)",
  role: "Rol",
  roleEs: "Rol (español)",
  email: "Email",
  phone: "Teléfono",
  imageUrl: "Foto",
  linkedinUrl: "LinkedIn",
  isPartner: "Socio",
  partnerSinceYear: "Socio desde",
  showPartnerSince: "Mostrar antigüedad de Socio",
  published: "Visible en el sitio",
  bioIntro: "Introducción",
  bioIntroEs: "Introducción (español)",
  bio: "Biografía",
  bioEs: "Biografía (español)",
  practiceGroupIds: "Áreas de práctica",
  industryGroupIds: "Industrias",
};

const partnerSinceYearInput = z.preprocess(
  (value) => value === "" || value === undefined ? null : value,
  z.coerce.number().int().min(PARTNER_SINCE_YEAR_MIN).max(PARTNER_SINCE_YEAR_MAX).nullable(),
);

export const teamMemberFormSchema = z.object({
  name: z.string().min(1, "Name is required"),
  givenNames: z.string().min(1, "Given name is required"),
  firstSurname: z.string().min(1, "First surname is required"),
  secondSurname: z.string().optional(),
  slug: z.string().min(1, "Slug is required"),
  title: z.string().min(1, "Title is required"),
  titleEs: z.string().min(1, "Spanish title is required"),
  role: z.string().min(1, "Role is required"),
  roleEs: z.string().min(1, "Spanish role is required"),
  email: z.string().email().optional().or(z.literal("")),
  phone: z.string().optional(),
  linkedinUrl: z.string().url().optional().or(z.literal("")),
  imageUrl: z.string().optional().or(z.literal("")),
  bio: z.string().optional(),
  bioEs: z.string().optional(),
  bioIntro: z.string().optional(),
  bioIntroEs: z.string().optional(),
  education: z.array(z.object({
    school: z.string(),
    schoolEs: z.string().optional(),
    degree: z.string(),
    degreeEs: z.string().optional(),
    year: z.string().optional(),
  })).default([]),
  affiliations: z.array(z.object({
    organization: z.string(),
    organizationEs: z.string().optional(),
    role: z.string().optional(),
    roleEs: z.string().optional(),
  })).default([]),
  rankings: z.array(z.object({
    publication: z.string(),
    ranking: z.string(),
    rankingEs: z.string().optional(),
    year: z.string().optional(),
    area: z.string().optional(),
    areaEs: z.string().optional(),
  })).default([]),
  publications: z.array(z.object({
    title: z.string(),
    titleEs: z.string().optional(),
    journal: z.string().optional(),
    year: z.string().optional(),
    url: z.string().optional(),
    kind: z.enum(["news", "article"]).optional(),
  })).default([]),
  languages: z.array(z.string()).default([]),
  languagesEs: z.array(z.string()).default([]),
  isPartner: z.boolean().default(false),
  partnerSinceYear: partnerSinceYearInput.default(null),
  showPartnerSince: z.boolean().default(true),
  published: z.boolean().default(true),
  order: z.coerce.number().min(0).default(0),
  practiceGroupIds: z.array(z.string()).default([]),
  industryGroupIds: z.array(z.string()).default([]),
});

export type TeamMemberFormData = z.infer<typeof teamMemberFormSchema>;
export type TeamFormCopy = typeof teamFormTranslations.en | typeof teamFormTranslations.es;

export function createTeamMemberDefaults(): TeamMemberFormData {
  return {
    name: "",
    givenNames: "",
    firstSurname: "",
    secondSurname: "",
    slug: "",
    title: "",
    titleEs: "",
    role: "",
    roleEs: "",
    email: "",
    phone: "",
    linkedinUrl: "",
    imageUrl: "",
    bio: "",
    bioEs: "",
    bioIntro: "",
    bioIntroEs: "",
    education: [],
    affiliations: [],
    rankings: [],
    publications: [],
    languages: [],
    languagesEs: [],
    isPartner: false,
    partnerSinceYear: null,
    showPartnerSince: true,
    published: true,
    order: 0,
    practiceGroupIds: [],
    industryGroupIds: [],
  };
}
